version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./odoo_data:/var/lib/odoo
      - .:/mnt/extra-addons
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.4
  mydb:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
  bot:
    container_name: bot_container
    build: .
    restart: always
    environment:
      - TOKEN=6121965837:AAHb8i_Uh2V9CiizQFNQopyC4BDA6eCSTbg
      - URL=http://172.16.1.4:8069/
      - DB=tt
      - ODOO_USER=gusakvd@gmail.com
      - PASSWORD=123

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
